name: Playwright BDD Cucumber Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:

  cucumber-tests:

    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Dependencies
        run: npm ci


      - name: Install Playwright Browsers
        run: npx playwright install --with-deps


      - name: Run Cucumber BDD Tests
        run: npx cucumber-js 
      
        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: cucumber-report
          path: |
            reports/
            screenshots/
            videos/
